### ISSUE TITLE
Update license information in PHP files

### ISSUE THREAD

**Issue by roxblnfk** [cycle/schema-provider#3]
This repository is the result of extracting the Schema Provider files from the `yiisoft/yii-cycle` repository, which is licensed under [`BSD 3-Clause`](https://github.com/yiisoft/yii-cycle/edit/master/LICENSE.md).
Despite the fact that the extracted code in `yiisoft/yii-cycle` was originally written by me, it seems we still need to place a bunch of placeholders in all the base files.

**Comment by samdark** [comment]
Feel free not to do it if it's a hassle and re-license the code under MIT.

**Comment by roxblnfk** [comment]
@samdark thank you, you've saved us valuable time.
Well then, @msmakouz we are ready for the release.
